# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.1.1
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: manucool123.rich@gmail.com
author_name: Manav Goyal
preset_name: starter
project_name: algointent

